apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: default
  labels:
    name: pvc-claim
spec:
  accessModes:
  - ReadWriteOnce
  volumeMode: Filesystem
  selector:
    matchLabels:
      vol: host
  resources:
    requests:
      storage: "1Gi"