apiVersion: v1
kind: Pod
metadata:
  name: pvc-pod
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          cpu: "200m"
          memory: "200M"
        limits:
          cpu: "200m"
          memory: "200M"
      volumeMounts:
        - name:  pvc-vol
          mountPath:  /pvc
  volumes:
      - name: pvc-vol
        persistentVolumeClaim:
          claimName: awd-ebs-pvc