apiVersion: v1
kind: Service
metadata:
  name:  headless-service
  namespace: new
  labels:
    app: quarkus-statefulset
spec:
  selector:
    app:  quarkus-statefulset
  clusterIP: None
  ports:
  - name:  web
    port:  80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: new
spec:
  selector:
    matchLabels:
      app: quarkus-statefulset # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: quarkus-statefulset # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
          name: web
        # volumeMounts:
        # - name: www
        #   mountPath: /usr/share/nginx/html
  # volumeClaimTemplates:
  # - metadata:
  #     name: www
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: "my-storage-class"
  #     resources:
  #       requests:
  #         storage: 1Gi