apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: server
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io2
  iopsPerGB: "40"
  fsType: "ext4"
  encrypted: "true"
reclaimPolicy: "Retain"
