apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: awd-ebs-pvc
  namespace: default
  labels:
    sc: ebs
spec:
  storageClassName: myclass
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi